columns:
  - id: int
  - Gender: category
  - Age: int
  - Driving_License: int
  - Region_Code: float
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int

numerical_columns:
  - Age
  - Driving_License
  - Previously_Insured
  - Vintage
  - Response

categorical_column:
  - Vehicle_Age
  - Gender
  - Vehicle_Damage

drop_columns: _id

num_features:
  - Age
  - Vintage

mm_columns:
  - Annual_Premium
  

